### ISSUE TITLE
Doge balance not reflecting

### ISSUE THREAD

**Issue by Gimme8008135** [dpalwallet/DPalWallet#13]
I had minted a few tokens and everything is going well, then i decided to transfer 1 doge from my dpal wallet to exchange account and it's pending for almost a month and then after 3-4 days of execution of transfer my 
70 dogecoin balance is also gone it is currently 0.056 doge, and the transaction is still pending it's been a month now.

**Comment by dpalwallet** [comment]
reset your wallet at settings page
