### ISSUE TITLE
I imported a wallet I used for doginals but the inscriptions do not show

### ISSUE THREAD

**Issue by ChristianGrieger** [dpalwallet/DPalWallet#3]
Any idea why my inscriptions created with doginals wallet are not showing up?

**Comment by dpalwallet** [comment]
Data sync slow

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Christian ***@***.***>
寄件日期: Saturday, May 13, 2023 5:13:03 PM
收件者: dpalwallet/DPalWallet ***@***.***>
副本: Subscribed ***@***.***>
主旨: [dpalwallet/DPalWallet] I imported a wallet I used for doginals but the inscriptions do not show (Issue #3)


Any idea why my inscriptions created with doginals wallet are not showing up?

**Comment by ChristianGrieger** [comment]
Data is synced. but not showing up the inscriptions. So you use the same protocol as doginals wallet? Just o be sure.

**Comment by dpalwallet** [comment]
Yes

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Christian ***@***.***>
寄件日期: Saturday, May 13, 2023 5:15:40 PM
收件者: dpalwallet/DPalWallet ***@***.***>
副本: dpalwallet ***@***.***>; Comment ***@***.***>
主旨: Re: [dpalwallet/DPalWallet] I imported a wallet I used for doginals but the inscriptions do not show (Issue #3)


Data is synced. but not showing up the inscriptions. So you use the same protocol as doginals wallet? Just o be sure.

**Comment by ChristianGrieger** [comment]
okay thanks :) Also your discord does not allow to write messages, maybe you should check that. Thank you.

**Comment by dpalwallet** [comment]
I don’t have discord

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Christian ***@***.***>
寄件日期: Saturday, May 13, 2023 5:23:32 PM
收件者: dpalwallet/DPalWallet ***@***.***>
副本: dpalwallet ***@***.***>; Comment ***@***.***>
主旨: Re: [dpalwallet/DPalWallet] I imported a wallet I used for doginals but the inscriptions do not show (Issue #3)


okay thanks :) Also your discord does not allow to write messages, maybe you should check that. Thank you.

**Comment by ChristianGrieger** [comment]
okay so its from an external user who created it :) np.

**Comment by ChristianGrieger** [comment]
Will you check why existing doginals not show even if they are text?

**Comment by ChristianGrieger** [comment]
There are 1111 inscriptions for address -> DAzMhMDWSKKN2CZe994MP8mwFuJgLBZRue

Example: https://dogecoin.earlyordies.com/content/6cfe7897d8b44632bd9706ceef6635dddc6a9f6efbc1f100ef10626f7c77996ai0

But none of them show in the chrome app after sync.
