### ISSUE TITLE
Image inscritions support

### ISSUE THREAD

**Issue by ChristianGrieger** [dpalwallet/DPalWallet#4]
The wallet only allows to create text inscriptions. What about images?

**Comment by dpalwallet** [comment]
Other media not safe enough for your wallet

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Christian ***@***.***>
寄件日期: Saturday, May 13, 2023 5:13:33 PM
收件者: dpalwallet/DPalWallet ***@***.***>
副本: Subscribed ***@***.***>
主旨: [dpalwallet/DPalWallet] Image inscritions support (Issue #4)


The wallet only allows to create text inscriptions. What about images?

**Comment by ChristianGrieger** [comment]
hmkay :/
