### ISSUE TITLE
balance not reflecting

### ISSUE THREAD

**Issue by Aburoberlin** [dpalwallet/DPalWallet#5]
i had done some inscription earlier yesterday,wanted to mint new tokens but i cant seem to find my doge in my wallet

**Comment by dpalwallet** [comment]
check this

https://github.com/dpalwallet/DoginalsPlan/blob/main/faq.md




取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Aburoberlin ***@***.***>
寄件日期: Sunday, May 14, 2023 4:12:29 AM
收件者: dpalwallet/DPalWallet ***@***.***>
副本: Subscribed ***@***.***>
主旨: [dpalwallet/DPalWallet] balance not reflecting (Issue #5)


i had done some inscription earlier yesterday,wanted to mint new tokens but i cant seem to find my doge in my wallet

**Comment by Aburoberlin** [comment]
thank you sir
