### ISSUE TITLE
minted tokens not showing in my wallet

### ISSUE THREAD

**Issue by Aburoberlin** [dpalwallet/DPalWallet#6]
all the tokens i minted yesterday and earlier this morning is not showing in my wallet,does that mean i have to start all over???

**Comment by dpalwallet** [comment]
What u have done

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Aburoberlin ***@***.***>
寄件日期: Sunday, May 14, 2023 4:14:56 AM
收件者: dpalwallet/DPalWallet ***@***.***>
副本: Subscribed ***@***.***>
主旨: [dpalwallet/DPalWallet] minted tokens not showing in my wallet (Issue #6)


all the tokens i minted yesterday and earlier this morning is not showing in my wallet,does that mean i have to start all over???

**Comment by Aburoberlin** [comment]
please can you resend the linkto my email: ayomikunlawalson@outlook.com..i am unable to view it here
