### ISSUE TITLE
If u have problem dont push issue just join group

### ISSUE THREAD

**Issue by dpalwallet** [dpalwallet/DPalWallet#9]
https://t.me/dpalwallet

only this no others

**Comment by hamza478478** [comment]
Not answering on telegram the mint ordinal button is not showing

**Comment by ThomasLuuu** [comment]
@hamza478478 the mint button is paused for updating.

**Comment by Babakrypto** [comment]
Hello there, I inscribed the ordinals via Dpal and while usiing the indexer , i cannot find any rewards. 
![Screenshot (25)](https://github.com/dpalwallet/DPalWallet/assets/98531159/428c2be2-3479-4721-8375-00f2a181546e)
![Screenshot (26)](https://github.com/dpalwallet/DPalWallet/assets/98531159/f180a5b3-b336-4af8-98ec-f657ec318367)
